#
/control/verbose 0
/control/saveHistory
/run/verbose 0

# define the detector geometry
/detector/setOuterCryostatRadius 150 cm
/detector/setOuterCryostatHeight 300 cm
/detector/setOuterCryostatWallThickness 10 mm

/detector/setInnerCryostatRadius 120 cm
/detector/setInnerCryostatHeight 240 cm
/detector/setInnerCryostatWallThickness 6 mm

/detector/setFiducialRadius 100 cm
/detector/setFiducialHeight 200 cm

/run/initialize

# define the particle gun settings
/gps/particle gamma
/gps/energy 1.0 MeV
/gps/pos/type Point
/gps/pos/centre 1193.99 0. 0. mm
/gps/direction -1 0 0

# output filename
/run/setOutputFileName /data/xenon/acolijn/G4FastSim/standard/standard_pencil.root
# fast simulation?
/run/setFastSimulation false

# run the thing...............
/run/printProgress 10000
/run/beamOn 100000

