# You can set these variables from the command line.
SPHINXOPTS    =
SPHINXBUILD   = sphinx-build
SOURCEDIR     = source
BUILDDIR      = build

# Option to specify the location of conf.py
SPHINXPROJ    = G4FastSim
CONF          = ../docs/conf.py   # Point to conf.py in docs/

# Build the HTML output
html:
	$(SPHINXBUILD) -b html -c . $(SOURCEDIR) $(BUILDDIR)/html

